### ISSUE TITLE
Falta un miembro de vuestro equipo

### ISSUE THREAD

**Issue by MPerezMateo** [aigora/twQ103-inmobiliaria#1]
Angélica no se ha unido aún. Recordad que debe unirse mediante moodle en el apartado Trabajo en Equipo para que los profesores la puedan ver y corregir.

**Comment by Juliauru** [comment]
Sigue faltando un miembro, y el plazo termina esta semana. Si no tiene un usuario registrado no podrá ser evaluada.

**Comment by crism98** [comment]
llevamos toda la semana intentado que Angelica pueda unirse al grupo, pero el enlace de molde ya no está y no conseguimos que pueda unirse. Le mandamos un correo a Raquel pero aún no nos contesta. Esta tarde iremos al laboratorio a las 5:30 para poder solucionar esto. Gracias.
